version: '3'

services:
  consul-agent-1: &consul-agent
    image: consul:latest
  consul:
    <<: *consul-agent
    networks:
      - consul-demo
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 1 -ui -client 0.0.0.0"

  fabio:
    networks:
      - consul-demo
    depends_on:
      - consul
    image: magiconair/fabio
    ports:
      - "9999:9999"
      - "9998:9998"
    volumes:
      - "./fabio.properties:/etc/fabio/fabio.properties"
    environment:
      - SERVICE_9998_TAGS=urlprefix-/fabio

networks:
  consul-demo:
